# Makefile for the FT8201 Incell driver.

obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)   +=  focaltech_point_report_check.o

obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT8201)   +=  focaltech_flash/
