/*
 *
 * This file contains definitions for hardware register fields defined in
 * DEBUGLOG register yml file. They are automatically extracted by gen_reg.
 *
 */

#ifndef __IAXXX_REGISTER_DEFS_DEBUGLOG_H__
#define __IAXXX_REGISTER_DEFS_DEBUGLOG_H__

/*** The base address for this set of registers ***/
#define IAXXX_DEBUGLOG_REGS_ADDR (0x0a000000)

/*** DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR (0x0a000000) ***/
/*
 * Gives the start address of Debug trace log buffer for Update Block 0.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_ADDR (0x0a000000)
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_BLOCK_0_DEBUGLOG_ADDR_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_BLOCK_0_DEBUGLOG_ADDR_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_BLOCK_0_DEBUGLOG_ADDR_POS 0
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_BLOCK_0_DEBUGLOG_ADDR_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_ADDR_BLOCK_0_DEBUGLOG_ADDR_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE (0x0a000004) ***/
/*
 * Gives the size of Debug trace log buffer for Update Block 0.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_ADDR (0x0a000004)
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_BLOCK_0_DEBUGLOG_SIZE_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_BLOCK_0_DEBUGLOG_SIZE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_BLOCK_0_DEBUGLOG_SIZE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_BLOCK_0_DEBUGLOG_SIZE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_0_DEBUGLOG_SIZE_BLOCK_0_DEBUGLOG_SIZE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR (0x0a000008) ***/
/*
 * Gives the start address of Debug trace log buffer for Update Block 1.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_ADDR (0x0a000008)
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_BLOCK_1_DEBUGLOG_ADDR_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_BLOCK_1_DEBUGLOG_ADDR_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_BLOCK_1_DEBUGLOG_ADDR_POS 0
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_BLOCK_1_DEBUGLOG_ADDR_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_ADDR_BLOCK_1_DEBUGLOG_ADDR_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE (0x0a00000c) ***/
/*
 * Gives the size of Debug trace log buffer for Update Block 1.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_ADDR (0x0a00000c)
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_BLOCK_1_DEBUGLOG_SIZE_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_BLOCK_1_DEBUGLOG_SIZE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_BLOCK_1_DEBUGLOG_SIZE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_BLOCK_1_DEBUGLOG_SIZE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_1_DEBUGLOG_SIZE_BLOCK_1_DEBUGLOG_SIZE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR (0x0a000010) ***/
/*
 * Gives the start address of Debug trace log buffer for Update Block 2.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_ADDR (0x0a000010)
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_BLOCK_2_DEBUGLOG_ADDR_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_BLOCK_2_DEBUGLOG_ADDR_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_BLOCK_2_DEBUGLOG_ADDR_POS 0
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_BLOCK_2_DEBUGLOG_ADDR_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_ADDR_BLOCK_2_DEBUGLOG_ADDR_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE (0x0a000014) ***/
/*
 * Gives the size of Debug trace log buffer for Update Block 2.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_ADDR (0x0a000014)
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_BLOCK_2_DEBUGLOG_SIZE_MASK \
	0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_BLOCK_2_DEBUGLOG_SIZE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_BLOCK_2_DEBUGLOG_SIZE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_BLOCK_2_DEBUGLOG_SIZE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_2_DEBUGLOG_SIZE_BLOCK_2_DEBUGLOG_SIZE_DECL (31 : 0)

/*** DEBUGLOG_DEBUG_LEVEL (0x0a000018) ***/
/*
 * Gives the Debug level.
 */
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_ADDR (0x0a000018)
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_MASK_VAL 0x00000fff
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_RMASK_VAL 0x00000fff
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_RESET_VAL 0x00000000

/*
 * Gives the Debug level for Update Block 0.
 */
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_0_DEBUG_LEVEL_MASK 0x0000000f
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_0_DEBUG_LEVEL_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_0_DEBUG_LEVEL_POS 0
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_0_DEBUG_LEVEL_SIZE 4
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_0_DEBUG_LEVEL_DECL (3 : 0)

/*
 * Gives the Debug level for Update Block 1.
 */
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_1_DEBUG_LEVEL_MASK 0x000000f0
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_1_DEBUG_LEVEL_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_1_DEBUG_LEVEL_POS 4
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_1_DEBUG_LEVEL_SIZE 4
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_1_DEBUG_LEVEL_DECL (7 : 4)

/*
 * Gives the Debug level for Update Block 2.
 */
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_2_DEBUG_LEVEL_MASK 0x00000f00
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_2_DEBUG_LEVEL_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_2_DEBUG_LEVEL_POS 8
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_2_DEBUG_LEVEL_SIZE 4
#define IAXXX_DEBUGLOG_DEBUG_LEVEL_BLOCK_2_DEBUG_LEVEL_DECL (11 : 8)

/*** DEBUGLOG_BLOCK_0_CRASHLOG_ADDR (0x0a00001c) ***/
/*
 * Gives the start address of Crash log buffer for Update Block 0 core
 */
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_ADDR (0x0a00001c)
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_ADDR_MODE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_0_CRASHLOG_SIZE (0x0a000020) ***/
/*
 * Gives the size of Crash log buffer for Update Block 0 core.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_ADDR (0x0a000020)
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_0_CRASHLOG_SIZE_MODE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_1_CRASHLOG_ADDR (0x0a000024) ***/
/*
 * Gives the start address of Crash log buffer for Update Block 1 core
 */
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_ADDR (0x0a000024)
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_ADDR_MODE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_1_CRASHLOG_SIZE (0x0a000028) ***/
/*
 * Gives the size of Crash log buffer for Update Block 1 core.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_ADDR (0x0a000028)
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_1_CRASHLOG_SIZE_MODE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_2_CRASHLOG_ADDR (0x0a00002c) ***/
/*
 * Gives the start address of Crash log buffer for Update Block 2 core
 */
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_ADDR (0x0a00002c)
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_RESET_VAL 0x00000000

/*
 * Start Address of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_ADDR_MODE_DECL (31 : 0)

/*** DEBUGLOG_BLOCK_2_CRASHLOG_SIZE (0x0a000030) ***/
/*
 * Gives the size of Crash log buffer for Update Block 2 core.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_ADDR (0x0a000030)
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_RMASK_VAL 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_WMASK_VAL 0x00000000
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_RESET_VAL 0x00000000

/*
 * Size of RecorderData struct.
 */
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MODE_MASK 0xffffffff
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MODE_RESET_VAL 0x0
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MODE_POS 0
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MODE_SIZE 32
#define IAXXX_DEBUGLOG_BLOCK_2_CRASHLOG_SIZE_MODE_DECL (31 : 0)

/* Number of registers in the module */
#define IAXXX_DEBUGLOG_REG_NUM 13

#endif /* __SW_REGISTER_DEFS_DEBUGLOG_H__ */
