/*
 * iaxxx-register-defs-channel-header.h
 *
 * Copyright 2017 Knowles Corporation
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 */

/*
 *
 * AUTO-GENERATED BY gen_reg_header. DO NOT EDIT.
 *
 * sw_register_defs_CH_HDR.h
 *
 * This file contains definitions for hardware register fields defined in
 * CH_HDR register yml file. They are automatically extracted by gen_reg.
 *
 */
#ifndef __IAXXX_REGISTER_DEFS_CH_HDR_H__
#define __IAXXX_REGISTER_DEFS_CH_HDR_H__

/*** The base address for this set of registers ***/
#define IAXXX_CH_HDR_REGS_ADDR 0x01000000

/*** CH_HDR_CH_CNT (0x01000000) ***/
/*
 * Number of channel groups in the channel block.
 */
#define IAXXX_CH_HDR_CH_CNT_ADDR 0x01000000
#define IAXXX_CH_HDR_CH_CNT_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_RESET_VAL 0x00000000

/*
 * Number of channel groups in the channel block.
 */
#define IAXXX_CH_HDR_CH_CNT_REG_MASK 0xffffffff
#define IAXXX_CH_HDR_CH_CNT_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_CNT_REG_POS 0
#define IAXXX_CH_HDR_CH_CNT_REG_SIZE 32

/*** CH_HDR_CH_EN (0x01000004) ***/
/*
 * Enable/Disable Channels.
 */
#define IAXXX_CH_HDR_CH_EN_ADDR 0x01000004
#define IAXXX_CH_HDR_CH_EN_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_EN_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_EN_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_EN_RESET_VAL 0x00000000

/*
 * Enable/Disable channel 0
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_0_REG_MASK 0x00000001
#define IAXXX_CH_HDR_CH_EN_0_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_0_REG_POS 0
#define IAXXX_CH_HDR_CH_EN_0_REG_SIZE 1

/*
 * Enable/Disable channel 1
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_1_REG_MASK 0x00000002
#define IAXXX_CH_HDR_CH_EN_1_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_1_REG_POS 1
#define IAXXX_CH_HDR_CH_EN_1_REG_SIZE 1

/*
 * Enable/Disable channel 2
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_2_REG_MASK 0x00000004
#define IAXXX_CH_HDR_CH_EN_2_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_2_REG_POS 2
#define IAXXX_CH_HDR_CH_EN_2_REG_SIZE 1

/*
 * Enable/Disable channel 3
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_3_REG_MASK 0x00000008
#define IAXXX_CH_HDR_CH_EN_3_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_3_REG_POS 3
#define IAXXX_CH_HDR_CH_EN_3_REG_SIZE 1

/*
 * Enable/Disable channel 4
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_4_REG_MASK 0x00000010
#define IAXXX_CH_HDR_CH_EN_4_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_4_REG_POS 4
#define IAXXX_CH_HDR_CH_EN_4_REG_SIZE 1

/*
 * Enable/Disable channel 5
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_5_REG_MASK 0x00000020
#define IAXXX_CH_HDR_CH_EN_5_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_5_REG_POS 5
#define IAXXX_CH_HDR_CH_EN_5_REG_SIZE 1

/*
 * Enable/Disable channel 6
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_6_REG_MASK 0x00000040
#define IAXXX_CH_HDR_CH_EN_6_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_6_REG_POS 6
#define IAXXX_CH_HDR_CH_EN_6_REG_SIZE 1

/*
 * Enable/Disable channel 7
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_7_REG_MASK 0x00000080
#define IAXXX_CH_HDR_CH_EN_7_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_7_REG_POS 7
#define IAXXX_CH_HDR_CH_EN_7_REG_SIZE 1

/*
 * Enable/Disable channel 8
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_8_REG_MASK 0x00000100
#define IAXXX_CH_HDR_CH_EN_8_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_8_REG_POS 8
#define IAXXX_CH_HDR_CH_EN_8_REG_SIZE 1

/*
 * Enable/Disable channel 9
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_9_REG_MASK 0x00000200
#define IAXXX_CH_HDR_CH_EN_9_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_9_REG_POS 9
#define IAXXX_CH_HDR_CH_EN_9_REG_SIZE 1

/*
 * Enable/Disable channel 10
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_10_REG_MASK 0x00000400
#define IAXXX_CH_HDR_CH_EN_10_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_10_REG_POS 10
#define IAXXX_CH_HDR_CH_EN_10_REG_SIZE 1

/*
 * Enable/Disable channel 11
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_11_REG_MASK 0x00000800
#define IAXXX_CH_HDR_CH_EN_11_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_11_REG_POS 11
#define IAXXX_CH_HDR_CH_EN_11_REG_SIZE 1

/*
 * Enable/Disable channel 12
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_12_REG_MASK 0x00001000
#define IAXXX_CH_HDR_CH_EN_12_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_12_REG_POS 12
#define IAXXX_CH_HDR_CH_EN_12_REG_SIZE 1

/*
 * Enable/Disable channel 13
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_13_REG_MASK 0x00002000
#define IAXXX_CH_HDR_CH_EN_13_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_13_REG_POS 13
#define IAXXX_CH_HDR_CH_EN_13_REG_SIZE 1

/*
 * Enable/Disable channel 14
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_14_REG_MASK 0x00004000
#define IAXXX_CH_HDR_CH_EN_14_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_14_REG_POS 14
#define IAXXX_CH_HDR_CH_EN_14_REG_SIZE 1

/*
 * Enable/Disable channel 15
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_15_REG_MASK 0x00008000
#define IAXXX_CH_HDR_CH_EN_15_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_15_REG_POS 15
#define IAXXX_CH_HDR_CH_EN_15_REG_SIZE 1

/*
 * Enable/Disable channel 16
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_16_REG_MASK 0x00010000
#define IAXXX_CH_HDR_CH_EN_16_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_16_REG_POS 16
#define IAXXX_CH_HDR_CH_EN_16_REG_SIZE 1

/*
 * Enable/Disable channel 17
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_17_REG_MASK 0x00020000
#define IAXXX_CH_HDR_CH_EN_17_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_17_REG_POS 17
#define IAXXX_CH_HDR_CH_EN_17_REG_SIZE 1

/*
 * Enable/Disable channel 18
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_18_REG_MASK 0x00040000
#define IAXXX_CH_HDR_CH_EN_18_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_18_REG_POS 18
#define IAXXX_CH_HDR_CH_EN_18_REG_SIZE 1

/*
 * Enable/Disable channel 19
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_19_REG_MASK 0x00080000
#define IAXXX_CH_HDR_CH_EN_19_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_19_REG_POS 19
#define IAXXX_CH_HDR_CH_EN_19_REG_SIZE 1

/*
 * Enable/Disable channel 20
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_20_REG_MASK 0x00100000
#define IAXXX_CH_HDR_CH_EN_20_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_20_REG_POS 20
#define IAXXX_CH_HDR_CH_EN_20_REG_SIZE 1

/*
 * Enable/Disable channel 21
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_21_REG_MASK 0x00200000
#define IAXXX_CH_HDR_CH_EN_21_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_21_REG_POS 21
#define IAXXX_CH_HDR_CH_EN_21_REG_SIZE 1

/*
 * Enable/Disable channel 22
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_22_REG_MASK 0x00400000
#define IAXXX_CH_HDR_CH_EN_22_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_22_REG_POS 22
#define IAXXX_CH_HDR_CH_EN_22_REG_SIZE 1

/*
 * Enable/Disable channel 23
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_23_REG_MASK 0x00800000
#define IAXXX_CH_HDR_CH_EN_23_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_23_REG_POS 23
#define IAXXX_CH_HDR_CH_EN_23_REG_SIZE 1

/*
 * Enable/Disable channel 24
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_24_REG_MASK 0x01000000
#define IAXXX_CH_HDR_CH_EN_24_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_24_REG_POS 24
#define IAXXX_CH_HDR_CH_EN_24_REG_SIZE 1

/*
 * Enable/Disable channel 25
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_25_REG_MASK 0x02000000
#define IAXXX_CH_HDR_CH_EN_25_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_25_REG_POS 25
#define IAXXX_CH_HDR_CH_EN_25_REG_SIZE 1

/*
 * Enable/Disable channel 26
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_26_REG_MASK 0x04000000
#define IAXXX_CH_HDR_CH_EN_26_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_26_REG_POS 26
#define IAXXX_CH_HDR_CH_EN_26_REG_SIZE 1

/*
 * Enable/Disable channel 27
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_27_REG_MASK 0x08000000
#define IAXXX_CH_HDR_CH_EN_27_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_27_REG_POS 27
#define IAXXX_CH_HDR_CH_EN_27_REG_SIZE 1

/*
 * Enable/Disable channel 28
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_28_REG_MASK 0x10000000
#define IAXXX_CH_HDR_CH_EN_28_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_28_REG_POS 28
#define IAXXX_CH_HDR_CH_EN_28_REG_SIZE 1

/*
 * Enable/Disable channel 29
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_29_REG_MASK 0x20000000
#define IAXXX_CH_HDR_CH_EN_29_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_29_REG_POS 29
#define IAXXX_CH_HDR_CH_EN_29_REG_SIZE 1

/*
 * Enable/Disable channel 30
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_30_REG_MASK 0x40000000
#define IAXXX_CH_HDR_CH_EN_30_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_30_REG_POS 30
#define IAXXX_CH_HDR_CH_EN_30_REG_SIZE 1

/*
 * Enable/Disable channel 31
 * 0 - Disable
 * 1 - Enable
 */
#define IAXXX_CH_HDR_CH_EN_31_REG_MASK 0x80000000
#define IAXXX_CH_HDR_CH_EN_31_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_EN_31_REG_POS 31
#define IAXXX_CH_HDR_CH_EN_31_REG_SIZE 1

/*** CH_HDR_CH_GAIN (0x01000008) ***/
/*
 * Trigger gain update for channels. Set by host, cleared by device.
 */
#define IAXXX_CH_HDR_CH_GAIN_ADDR 0x01000008
#define IAXXX_CH_HDR_CH_GAIN_MASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_RMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_WMASK_VAL 0xffffffff
#define IAXXX_CH_HDR_CH_GAIN_RESET_VAL 0x00000000

/*
 * Update gain for channel 0
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_0_REG_MASK 0x00000001
#define IAXXX_CH_HDR_CH_GAIN_0_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_0_REG_POS 0
#define IAXXX_CH_HDR_CH_GAIN_0_REG_SIZE 1

/*
 * Update gain for channel 1
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_1_REG_MASK 0x00000002
#define IAXXX_CH_HDR_CH_GAIN_1_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_1_REG_POS 1
#define IAXXX_CH_HDR_CH_GAIN_1_REG_SIZE 1

/*
 * Update gain for channel 2
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_2_REG_MASK 0x00000004
#define IAXXX_CH_HDR_CH_GAIN_2_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_2_REG_POS 2
#define IAXXX_CH_HDR_CH_GAIN_2_REG_SIZE 1

/*
 * Update gain for channel 3
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_3_REG_MASK 0x00000008
#define IAXXX_CH_HDR_CH_GAIN_3_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_3_REG_POS 3
#define IAXXX_CH_HDR_CH_GAIN_3_REG_SIZE 1

/*
 * Update gain for channel 4
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_4_REG_MASK 0x00000010
#define IAXXX_CH_HDR_CH_GAIN_4_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_4_REG_POS 4
#define IAXXX_CH_HDR_CH_GAIN_4_REG_SIZE 1

/*
 * Update gain for channel 5
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_5_REG_MASK 0x00000020
#define IAXXX_CH_HDR_CH_GAIN_5_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_5_REG_POS 5
#define IAXXX_CH_HDR_CH_GAIN_5_REG_SIZE 1

/*
 * Update gain for channel 6
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_6_REG_MASK 0x00000040
#define IAXXX_CH_HDR_CH_GAIN_6_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_6_REG_POS 6
#define IAXXX_CH_HDR_CH_GAIN_6_REG_SIZE 1

/*
 * Update gain for channel 7
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_7_REG_MASK 0x00000080
#define IAXXX_CH_HDR_CH_GAIN_7_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_7_REG_POS 7
#define IAXXX_CH_HDR_CH_GAIN_7_REG_SIZE 1

/*
 * Update gain for channel 8
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_8_REG_MASK 0x00000100
#define IAXXX_CH_HDR_CH_GAIN_8_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_8_REG_POS 8
#define IAXXX_CH_HDR_CH_GAIN_8_REG_SIZE 1

/*
 * Update gain for channel 9
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_9_REG_MASK 0x00000200
#define IAXXX_CH_HDR_CH_GAIN_9_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_9_REG_POS 9
#define IAXXX_CH_HDR_CH_GAIN_9_REG_SIZE 1

/*
 * Update gain for channel 10
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_10_REG_MASK 0x00000400
#define IAXXX_CH_HDR_CH_GAIN_10_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_10_REG_POS 10
#define IAXXX_CH_HDR_CH_GAIN_10_REG_SIZE 1

/*
 * Update gain for channel 11
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_11_REG_MASK 0x00000800
#define IAXXX_CH_HDR_CH_GAIN_11_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_11_REG_POS 11
#define IAXXX_CH_HDR_CH_GAIN_11_REG_SIZE 1

/*
 * Update gain for channel 12
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_12_REG_MASK 0x00001000
#define IAXXX_CH_HDR_CH_GAIN_12_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_12_REG_POS 12
#define IAXXX_CH_HDR_CH_GAIN_12_REG_SIZE 1

/*
 * Update gain for channel 13
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_13_REG_MASK 0x00002000
#define IAXXX_CH_HDR_CH_GAIN_13_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_13_REG_POS 13
#define IAXXX_CH_HDR_CH_GAIN_13_REG_SIZE 1

/*
 * Update gain for channel 14
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_14_REG_MASK 0x00004000
#define IAXXX_CH_HDR_CH_GAIN_14_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_14_REG_POS 14
#define IAXXX_CH_HDR_CH_GAIN_14_REG_SIZE 1

/*
 * Update gain for channel 15
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_15_REG_MASK 0x00008000
#define IAXXX_CH_HDR_CH_GAIN_15_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_15_REG_POS 15
#define IAXXX_CH_HDR_CH_GAIN_15_REG_SIZE 1

/*
 * Update gain for channel 16
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_16_REG_MASK 0x00010000
#define IAXXX_CH_HDR_CH_GAIN_16_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_16_REG_POS 16
#define IAXXX_CH_HDR_CH_GAIN_16_REG_SIZE 1

/*
 * Update gain for channel 17
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_17_REG_MASK 0x00020000
#define IAXXX_CH_HDR_CH_GAIN_17_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_17_REG_POS 17
#define IAXXX_CH_HDR_CH_GAIN_17_REG_SIZE 1

/*
 * Update gain for channel 18
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_18_REG_MASK 0x00040000
#define IAXXX_CH_HDR_CH_GAIN_18_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_18_REG_POS 18
#define IAXXX_CH_HDR_CH_GAIN_18_REG_SIZE 1

/*
 * Update gain for channel 19
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_19_REG_MASK 0x00080000
#define IAXXX_CH_HDR_CH_GAIN_19_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_19_REG_POS 19
#define IAXXX_CH_HDR_CH_GAIN_19_REG_SIZE 1

/*
 * Update gain for channel 20
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_20_REG_MASK 0x00100000
#define IAXXX_CH_HDR_CH_GAIN_20_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_20_REG_POS 20
#define IAXXX_CH_HDR_CH_GAIN_20_REG_SIZE 1

/*
 * Update gain for channel 21
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_21_REG_MASK 0x00200000
#define IAXXX_CH_HDR_CH_GAIN_21_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_21_REG_POS 21
#define IAXXX_CH_HDR_CH_GAIN_21_REG_SIZE 1

/*
 * Update gain for channel 22
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_22_REG_MASK 0x00400000
#define IAXXX_CH_HDR_CH_GAIN_22_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_22_REG_POS 22
#define IAXXX_CH_HDR_CH_GAIN_22_REG_SIZE 1

/*
 * Update gain for channel 23
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_23_REG_MASK 0x00800000
#define IAXXX_CH_HDR_CH_GAIN_23_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_23_REG_POS 23
#define IAXXX_CH_HDR_CH_GAIN_23_REG_SIZE 1

/*
 * Update gain for channel 24
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_24_REG_MASK 0x01000000
#define IAXXX_CH_HDR_CH_GAIN_24_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_24_REG_POS 24
#define IAXXX_CH_HDR_CH_GAIN_24_REG_SIZE 1

/*
 * Update gain for channel 25
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_25_REG_MASK 0x02000000
#define IAXXX_CH_HDR_CH_GAIN_25_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_25_REG_POS 25
#define IAXXX_CH_HDR_CH_GAIN_25_REG_SIZE 1

/*
 * Update gain for channel 26
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_26_REG_MASK 0x04000000
#define IAXXX_CH_HDR_CH_GAIN_26_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_26_REG_POS 26
#define IAXXX_CH_HDR_CH_GAIN_26_REG_SIZE 1

/*
 * Update gain for channel 27
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_27_REG_MASK 0x08000000
#define IAXXX_CH_HDR_CH_GAIN_27_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_27_REG_POS 27
#define IAXXX_CH_HDR_CH_GAIN_27_REG_SIZE 1

/*
 * Update gain for channel 28
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_28_REG_MASK 0x10000000
#define IAXXX_CH_HDR_CH_GAIN_28_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_28_REG_POS 28
#define IAXXX_CH_HDR_CH_GAIN_28_REG_SIZE 1

/*
 * Update gain for channel 29
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_29_REG_MASK 0x20000000
#define IAXXX_CH_HDR_CH_GAIN_29_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_29_REG_POS 29
#define IAXXX_CH_HDR_CH_GAIN_29_REG_SIZE 1

/*
 * Update gain for channel 30
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_30_REG_MASK 0x40000000
#define IAXXX_CH_HDR_CH_GAIN_30_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_30_REG_POS 30
#define IAXXX_CH_HDR_CH_GAIN_30_REG_SIZE 1

/*
 * Update gain for channel 31
 * 1 - request gain update
 */
#define IAXXX_CH_HDR_CH_GAIN_31_REG_MASK 0x80000000
#define IAXXX_CH_HDR_CH_GAIN_31_REG_RESET_VAL 0x0
#define IAXXX_CH_HDR_CH_GAIN_31_REG_POS 31
#define IAXXX_CH_HDR_CH_GAIN_31_REG_SIZE 1

/* Number of registers in the module */
#define IAXXX_CH_HDR_REG_NUM 3

#endif /* __IAXXX_REGISTER_DEFS_CH_HDR_H__ */
