#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#



obj-$(CONFIG_TOUCHSCREEN_FTS_INTERNAL_DEBUG) += src/
obj-$(CONFIG_TOUCHSCREEN_FTS_INTERNAL_DEBUG) += supported_ic/

