# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_CS47L15_CODEC)	+= switch-madera.o
obj-$(CONFIG_CS47L35_CODEC)	+= switch-madera.o

