/**
 * dbmdx7_fw_api.h
 *
 * Copyright (C) 2016 DSP Group
 * All rights reserved.
 *
 * Unauthorized copying of this file is strictly prohibited.
 */

#ifndef _DBMD7_FW_API_H
#define _DBMD7_FW_API_H

#define ERROR_CODE_GROUP_FW			0x0000
#define ERROR_CODE_GROUP_MAILBOX		0x0100
#define ERROR_CODE_GROUP_RTOS			0x0200
#define ERROR_CODE_GROUP_DMEM			0x0300
#define ERROR_CODE_GROUP_MSG			0x0400
#define ERROR_CODE_GROUP_ADDON			0x0450

/* To be used as "or" (|) with register number */
#define PENDING_MSG_USED_MALLOC			(1<<31)
#define PENDING_MSG_ADDR_MASK			0x7FFFFFFF

#define MAX_RX_MSG_LEN				(1024+20)
#define MSG_ID_GROUP_SIZE			16
#define MSG_TYPE__GET_MESSAGE			0
#define MSG_TYPE__GET_MESSAGE4INDEX		1
#define MSG_TYPE__SEND_VAR_LAN_MSG		2
#define MSG_TYPE__SEND_VAR_LAN_MSG_ACK		3
#define MSG_TYPE__WRITE16			4
#define MSG_TYPE__WRITE32			5
#define MSG_TYPE__WRITE16_ACK			6
#define MSG_TYPE__WRITE32_ACK			7
#define MSG_ERROR___NO_FREE_TX_MSG_ENTRY	(ERROR_CODE_GROUP_MSG + 0x01)
#define MSG_ERROR__TX_MSG_TOO_LONG		(ERROR_CODE_GROUP_MSG + 0x02)
#define MSG_ERROR__RX_MSG_TOO_LONG		(ERROR_CODE_GROUP_MSG + 0x03)
#define MSG_ERROR__WRONG_MSG_HEADER3		(ERROR_CODE_GROUP_MSG + 0x04)
#define MSG_ERROR__TX_MESSAGE_NOT_FOUND		(ERROR_CODE_GROUP_MSG + 0x05)
#define MSG_ERROR__IH_MSG_TOO_LONG		(ERROR_CODE_GROUP_MSG + 0x06)
#define MSG_ERROR__BAD_INTERFACE_NUM1		(ERROR_CODE_GROUP_MSG + 0x08)


#define ADDON_ERROR_BAD_CHANNEL_ORDER_CRITICAL	(ERROR_CODE_GROUP_ADDON + 0x20)
#define ADDON_ERROR_BAD_CHANNEL_ORDER		(ERROR_CODE_GROUP_ADDON + 0x30)
/* Algo specific non critical errors */
#define ADDON_ERROR_AWB_NOT_LOADED     (ERROR_CODE_GROUP_ADDON + 0x38)

#define MSG_ID_FW				0
#define MSG_ID_MAILBOX				1
#define MSG_ID_RTOS				2
#define MSG_ID_RES				3
#define MSG_ID_ADDON_FB				4

/************* Add-on Read Write  Registers ***************************/
#define ADDON_VERSION_NUMBER		0x0
#define ALGO_VERSION_NUMBER		0x1
#define SET_ACTIVE_USECASE_ID		0x8
#define SET_MIC_GAIN_ID			0x7
#define SET_MIC_CAPTURE_PROPERTIES	0xA

#define RESET_CLOCK_COUNTER		0xC
#define READ_CLOCK_COUNTER		0xD
#define SET_PRIVACY_MODE                0xE

#define SET_TDM0_DATA_PROPERTIES	0x10
#define SET_TDM1_DATA_PROPERTIES	0x11
#define SET_TDM2_DATA_PROPERTIES	0x12
#define SET_TDM3_DATA_PROPERTIES	0x13
#define SET_TDM4_DATA_PROPERTIES	0x14
#define SET_TDM5_DATA_PROPERTIES	0x15
#define SET_TDM6_DATA_PROPERTIES	0x16
#define SET_TDM7_DATA_PROPERTIES	0x17

// Algo set/get
#define SET_ALGO_PARAM			0x3A
#define GET_ALGO_PARAM			0x3B
#define TEST_TIMEOUT_ERROR		0x3C
#define SET_GET_PARAM_READY		0x3D
#define SET_HDMI_AEC_REF                0x40
#define SET_INTERNAL_SPEAKER            0x41
#define SET_VOICE_DL                    0x42
#define SET_VOICE_UL                    0x43
#define SET_VOICE_ASSISTANT             0x44
#define SET_VOICE_ASSISTANT_REF         0x45
#define SET_UNPROCESSED_MIC             0x46
#define SET_AIB_METADATA                0x47
#define SET_HDMI_REF_CHANNELS           0x48

#define SET_SPK_VOLUME_LEVEL            0x49
#define SET_VOICE_CALL_TYPE             0x50
#define SET_ALGO_BYPASS                 0x51
#ifdef CONFIG_DBMDX_TILT
#define SET_TILT_ANGLE                  0x52
#endif
#ifdef CONFIG_DBMDX_TV_DETECT
#define SET_TVD_ALGO_ENABLE             0x53
#define SET_TVD_TRIGGER                 0x54
#define GET_TVD_STATE                   0x55
#define GET_TVD_STICKY_FLAG             0x56
#define GET_TVD_STICKY_PLAYBACK_GAIN    0x57
#endif
#define SET_RINGTONE_PLAYBACK           0x58
#define SET_HDMI_CONNECT                0x59
#define SET_PLATFORM_ID                 0x60
#define SET_FW_OVERRIDE                 0x61
#define GET_DSPG_HEALTH_STAT            0x63
#define STAX_REGRESSION_CTRL            0x65
#define STAX_AWB_CMD_SIZE               0x66
#define OUTPUT_ISSUE_REPORT             0x67
/************* End Read Write  Registers ***************************/

#define ERROR_CODE__NO_FREE_TX_MSG_ENTRY  (MSG_ERROR___NO_FREE_TX_MSG_ENTRY)
#define ERROR_CODE__TX_MSG_TOO_LONG	  (MSG_ERROR__TX_MSG_TOO_LONG)
#define ERROR_CODE__RX_MSG_TOO_LONG	  (MSG_ERROR__RX_MSG_TOO_LONG)
#define ERROR_CODE__WRONG_MSG_HEADER3	  (MSG_ERROR__WRONG_MSG_HEADER3)
#define ERROR_CODE__TX_MESSAGE_NOT_FOUND  (MSG_ERROR__TX_MESSAGE_NOT_FOUND)
#define ERROR_CODE__ERR1		  (MSG_ERROR__IH_MSG_TOO_LONG)
#define ERROR_CODE__IH_MSG_TOO_LONG	  (MSG_ERROR__IH_MSG_TOO_LONG)
#define ERROR_CODE__BAD_INTERFACE_NUM1	  (MSG_ERROR__BAD_INTERFACE_NUM1)

#define REG_FW__VERSION_NUMBER			0x00
 /* (0x01 | RUN_ON_IDLE_LOOP) */
#define REG_FW__SYS_OPERATION_MODE		0x01
#define REG_FW__MEMORY_MANAGEMENT		0x02
#define REG_FW__3				0x03
#define REG_FW__MIC_DIG_GAIN			0x04
#define REG_FW__DIRECT_MEMORY_ACCESS		0x05
#define REG_FW__DIRECT_APB_ACCESS		0x06
#define REG_FW__DIRECT_CPM_ACCESS		0x07
#define REG_FW__ACCESS_OTP			0x08
#define REG_FW__MAX_MSG_LENGTH			0x09
#define REG_FW__DSP_UTILIZATION			0x0A
#define REG_FW__MAXIMUM_SAMPLE_VALUE		0x0B
#define REG_FW__UART0_BAUD_RATE			0x0C
#define REG_FW__UART1_BAUD_RATE			0x0D
#define REG_FW__UART1_TYPE_ECHO			0x0E
#define REG_FW__ERROR_REPORT			0x0F
#define REG_FW__GENERAL_CONFIG_1		0x10
#define REG_FW__DATA_DUMPPING_CONFIG		0x11
#define REG_FW__DEBUG_PRINT_LEVEL		0x12
#define REG_FW__EVENT_LOG_MASK			0x13
#define REG_FW__GPIO_CONTROL			0x14
#define REG_FW__HOST_WAKEUP_GPIO		0x15
#define REG_FW__16				0x16
#define REG_FW__LOAD_CORE_TEST			0x17
#define REG_FW__DEBUG_REGISTER2			0x18
#define REG_FW__FW_ID				0x19
#define REG_FW__MIC_HPF				0x1A
#define REG_FW__DDF_DC_CALIB			0x1B
#define REG_FW__I2C_SERVICE			0x1C
#define REG_FW__CLK_IN_FREQ			0x1D
#define REG_FW__PRINTF_BUFFER_LENGTH		0x1E
#define REG_FW__PRINT_TDM_REG_INFO		0x1F
#define REG_FW__READ_MISSED_INT_CNT		0x20
#define REG_FW__RTC_ALARM_VALUE			0x21
#define REG_FW__PRINT_HOST_MESSAGE		0x22
#define REG_FW__CONFIG_MICS			0x24
#define REG_FW__DATA_WRITE_CAPTURE		0x26
#define REG_FW__ADDRESS_BREAK_POINT		0x27
#define REG_FW__HOST_IF_CONFIG			0x29
#define REG_FW__TDM_ACTIVATION			0x31
#define REG_FW__UPDATE_DIVIDERS			0x32
#define REG_FW__TDM_CONFIG_START		0x40
#define REG_FW__TDM_RX_START			0x40
#define REG_FW__TDM_TX_START			0x50
#define REG_FW__TDM_CONFIG_LAST			0x5F


#define REG_MB__MAX_NUM_OF_MB			0x00
#define REG_MB__CURRENT_NUM_OF_MB		0x01
#define REG_MB__TEMP_BUFF_LEN			0x02
#define REG_MB__DELETE_MB			0x03
#define REG_MB__CREATE_MB			0x04
#define REG_MB__RESET_STATE			0x05
#define REG_MB__RESET_READ0			0x06
#define REG_MB__RESET_READ1			0x07
#define REG_MB__APPEND_DATA			0x08
#define REG_MB__RESET_AND_WRITE			0x09
#define REG_MB__DIRECT_WRITE			0x0A
#define REG_MB__DIRECT_READ			0x0B
#define REG_MB__READ_DATA			0x0C
#define REG_MB__BACKLOG				0x0D
#define REG_MB__READ_SMP_CNT0			0x0E
#define REG_MB__READ_SMP_CNT1			0x0F
#define REG_MB__GET_MB_ADDRESS			0x10
#define REG_MB__GET_MB_SIZE0			0x11
#define REG_MB__GET_MB_SIZE1			0x12
#define REG_MB__WATERMARK			0x13
#define REG_MB__ATTRIBUTE			0x14
#define REG_MB__RTOS_READ_TASK			0x15
#define REG_MB__RTOS_WRITE_TASK			0x16
#define REG_MB__FRAME_ALIGNMENT			0x17
#define REG_MB__RECORDING_STATUS		0x18
#define REG_MB__SET_BACKLOG_BY_TICKS		0x19
#define REG_MB__DEBUG_STATUS			0x1A
#define REG_MB__INPLACE_READ_DATA		0x1B
#define REG_MB__PRINT_INFO			0x1F

#define MB_INDEX_MICS_1ST			1
#define MB_INDEX_MICS_LAST			4
#define MB_INDEX_MICS_1				(MB_INDEX_MICS_1ST + 0)
#define MB_INDEX_MICS_2				(MB_INDEX_MICS_1ST + 1)
#define MB_INDEX_MICS_3				(MB_INDEX_MICS_1ST + 2)
#define MB_INDEX_MICS_4				(MB_INDEX_MICS_1ST + 3)

#define MB_INDEX_TDM_0_RX_ID			(REG_FW__TDM_RX_START + 0)
#define MB_INDEX_TDM_1_RX_ID			(REG_FW__TDM_RX_START + 1)
#define MB_INDEX_TDM_2_RX_ID			(REG_FW__TDM_RX_START + 2)
#define MB_INDEX_TDM_3_RX_ID			(REG_FW__TDM_RX_START + 3)
#define MB_INDEX_TDM_4_RX_ID			(REG_FW__TDM_RX_START + 4)
#define MB_INDEX_TDM_5_RX_ID			(REG_FW__TDM_RX_START + 5)
#define MB_INDEX_TDM_6_RX_ID			(REG_FW__TDM_RX_START + 6)
#define MB_INDEX_TDM_7_RX_ID			(REG_FW__TDM_RX_START + 7)

#define MB_INDEX_TDM_0_TX_ID			(REG_FW__TDM_TX_START + 0)
#define MB_INDEX_TDM_1_TX_ID			(REG_FW__TDM_TX_START + 1)
#define MB_INDEX_TDM_2_TX_ID			(REG_FW__TDM_TX_START + 2)
#define MB_INDEX_TDM_3_TX_ID			(REG_FW__TDM_TX_START + 3)
#define MB_INDEX_TDM_4_TX_ID			(REG_FW__TDM_TX_START + 4)
#define MB_INDEX_TDM_5_TX_ID			(REG_FW__TDM_TX_START + 5)
#define MB_INDEX_TDM_6_TX_ID			(REG_FW__TDM_TX_START + 6)
#define MB_INDEX_TDM_7_TX_ID			(REG_FW__TDM_TX_START + 7)

#define REG_RTOS__CREATE			0x00
#define REG_RTOS__DELETE			0x01
#define REG_RTOS__NOTIFY			0x02
#define REG_RTOS__PRIORITY_R			0x03
#define REG_RTOS__PRIORITY_W			0x04
#define REG_RTOS__STATE_R			0x05
#define REG_RTOS__SUSPEND			0x06
#define REG_RTOS__RESUME			0x07
#define REG_RTOS__NAME_R			0x08
#define REG_RTOS__TAG_R				0x09
#define REG_RTOS__TAG_W				0x0A
#define REG_RTOS__CALL_HOOK			0x0B
#define REG_RTOS__NUMBER_R			0x0C
#define REG_RTOS__NUMBER_W			0x0D
#define REG_RTOS__PRI_INHERIT			0x0E
#define REG_RTOS__PRI_DISINHERIT		0x0F
#define REG_RTOS__QUE_ADD_TO_SET		0x10
#define REG_RTOS__QUE_GEN_CREATE		0x11
#define REG_RTOS__QUE_CREATE_SET		0x12
#define REG_RTOS__QUE_DELETE			0x13
#define REG_RTOS__QUE_GEN_RECEIVE		0x14
#define REG_RTOS__QUE_MESSAGES_WAITING		0x15
#define REG_RTOS__QUE_REMOVE_FROM_SET		0x16
#define REG_RTOS__QUE_GEN_RESET			0x17
#define REG_RTOS__QUE_SELECT_FROM_SET		0x18
#define REG_RTOS__QUE_GEN_SEND			0x19
#define REG_RTOS__QUE_SPACES_AVAILABLE		0x1A
#define REG_RTOS__QUE_CREATE_COUNT_SEM		0x1B
#define REG_RTOS__QUE_CREATE_MUTEX		0x1C
#define REG_RTOS__TIMER_GEN_CMD			0x1D
#define REG_RTOS__TIMER_CREATE			0x1E
#define REG_RTOS__TIMER_ID_R			0x1F
#define REG_RTOS__TIMER_ACTIVE_R		0x20
#define REG_RTOS__PRIORITY_ISR_R		0x21
#define REG_RTOS__RESUME_ISR			0x22
#define REG_RTOS__SEND_QUEUE_NOTIFY		0x23
#define REG_RTOS__GET_TICK_COUNT		0x24
#define REG_RTOS__STK_HI_MARK_R			0x25
#define REG_RTOS__TASK_STATISTIC		0x26
#define REG_RTOS__RESET_TASKS_CLOCK		0x27
#define REG_RTOS__REPORT_TASK_QUEUE		0x30
#define REG_RTOS__CPU_CYCLE_CNT_SHIFT		0x31
#define REG_RTOS__TIMER_FREQ			0x32 /* | RUN_ON_IDLE_LOOP */


#define FW_ERROR__ADDR_OVERLAP			(ERROR_CODE_GROUP_FW + 0x01)
#define FW_ERROR__DMEM_CONFIG_OVERRUN		(ERROR_CODE_GROUP_FW + 0x02)
#define FW_ERROR__DMEM_OVERRUN_ADDON		(ERROR_CODE_GROUP_FW + 0x03)
#define FW_ERROR__BAD_CONFIG_PARAMS		(ERROR_CODE_GROUP_FW + 0x04)
#define FW_ERROR__BAD_MSG_LENGTH		(ERROR_CODE_GROUP_FW + 0x05)
#define FW_ERROR__RTOS_STACK_OVERFLOW		(ERROR_CODE_GROUP_FW + 0x06)
#define FW_ERROR__SAMPLES_PACK			(ERROR_CODE_GROUP_FW + 0x07)
#define FW_ERROR__SAMPLES_UNPACK		(ERROR_CODE_GROUP_FW + 0x08)
#define FW_ERROR__CANT_ALLOC_CONN_POINT		(ERROR_CODE_GROUP_FW + 0x09)
#define FW_ERROR__CANT_RELEASE_CONN_POINT	(ERROR_CODE_GROUP_FW + 0x0A)
#define FW_ERROR__FILTER_PARAMS			(ERROR_CODE_GROUP_FW + 0x0B)
#define FW_ERROR__NO_INT_DIV_FOUND		(ERROR_CODE_GROUP_FW + 0x0C)
#define FW_ERROR__RESAMPLING_TASK		(ERROR_CODE_GROUP_FW + 0x0D)
#define FW_ERROR__OVERRUN_ADDR_ZERO		(ERROR_CODE_GROUP_FW + 0x0E)
#define FW_ERROR__MIC_MB_NCH_NEQ		(ERROR_CODE_GROUP_FW + 0x0F)
#define FW_ERROR__TDM_ALREADY_CONFIGURED	(ERROR_CODE_GROUP_FW + 0x10)
#define FW_ERROR__TDM_NUM_CH_NOT_124		(ERROR_CODE_GROUP_FW + 0x11)
#define FW_ERROR__MB_NCH_ON_MB_OVER_TASK	(ERROR_CODE_GROUP_FW + 0x12)
#define FW_ERROR__MALLOC_NOT_SUPPORTED		(ERROR_CODE_GROUP_FW + 0x13)
#define FW_ERROR__SMP_FREQ_NOT_EQUAL		(ERROR_CODE_GROUP_FW + 0x14)
#define FW_ERROR__NREQ_IS_ZERO			(ERROR_CODE_GROUP_FW + 0x15)
#define FW_ERROR__NO_TDM0_CLOCK			(ERROR_CODE_GROUP_FW + 0x16)
#define FW_ERROR__UART1_BUFF_FULL		(ERROR_CODE_GROUP_FW + 0x17)
#define FW_ERROR__NCH_MB_CFG_NOT_0		(ERROR_CODE_GROUP_FW + 0x18)
#define FW_ERROR__SMP_COUNT_TOO_BIT		(ERROR_CODE_GROUP_FW + 0x19)
#define FW_ERROR__REC_MAILBOX_TOO_SMALL		(ERROR_CODE_GROUP_FW + 0x20)
#define FW_ERROR__CONN_POINT_ATTR_NO_MATCH	(ERROR_CODE_GROUP_FW + 0x21)
#define FW_ERROR__CONN_POINT_NOT_SUPPORTED	(ERROR_CODE_GROUP_FW + 0x22)
#define FW_ERROR__CMD_TO_TASK_FAILED            (ERROR_CODE_GROUP_FW + 0x2A)
#define FW_ERROR__BRANCH_TO_ZERO                (ERROR_CODE_GROUP_FW + 0x2B)
#define FW_ERROR__PRINTF_MB_ERROR1              (ERROR_CODE_GROUP_FW + 0x31)
#define FW_ERROR__PRINTF_MB_SIZE_LIMIT          (ERROR_CODE_GROUP_FW + 0x32)

#define UART_DEBUG_PRINTF			0x01
#define UART_DEBUG_ISR_IN_OUT			0x02
#define UART_DEBUG_MB_INFO_ON_NOTIFY		0x04
#define UART_DEBUG_MAILBOX_FULL_INFO		0x10
#define UART_DEBUG_HOST_COMMANDS		0x20
#define UART_DEBUG_RTOS_NOTIFY			0x40
#define UART_DEBUG_WAIT_COMPLETE		0x80


#define MB_ERROR__MB_IN_USE		(ERROR_CODE_GROUP_MAILBOX + 0x00)
#define MB_ERROR__NO_FREE_ENTRY		(ERROR_CODE_GROUP_MAILBOX + 0x02)
#define MB_ERROR__MB_ALREADY_EXIST	(ERROR_CODE_GROUP_MAILBOX + 0x03)
#define MB_ERROR__ILLIGAL_MB_ID		(ERROR_CODE_GROUP_MAILBOX + 0x04)
#define MB_ERROR__ALIGNMENT_ERROR	(ERROR_CODE_GROUP_MAILBOX + 0x05)
#define MB_ERROR__NO_SPACE_TO_WRITE	(ERROR_CODE_GROUP_MAILBOX + 0x06)
#define MB_ERROR__ATTRIB_NOT_SET	(ERROR_CODE_GROUP_MAILBOX + 0x07)
#define MB_ERROR__ILLIGAL_REG_NUM	(ERROR_CODE_GROUP_MAILBOX + 0x08)
#define MB_ERROR__MSG_TOO_SHORT		(ERROR_CODE_GROUP_MAILBOX + 0x09)
#define MB_ERROR__REG_9_ERR1		(ERROR_CODE_GROUP_MAILBOX + 0x0A)
#define MB_ERROR__REG_9_ERR2		(ERROR_CODE_GROUP_MAILBOX + 0x0B)
#define MB_ERROR__READ_UNDERRUN		(ERROR_CODE_GROUP_MAILBOX + 0x0C)
#define MB_ERROR__READ_ALIGNMENT	(ERROR_CODE_GROUP_MAILBOX + 0x0D)
#define MB_ERROR__WRITE_ALIGNMENT	(ERROR_CODE_GROUP_MAILBOX + 0x0E)
#define MB_ERROR__BUFFER_OVF_A_CLI0	(ERROR_CODE_GROUP_MAILBOX + 0x0F)
#define MB_ERROR__BUFFER_OVF_B_CLI0	(ERROR_CODE_GROUP_MAILBOX + 0x10)
#define MB_ERROR__BUFFER_OVERFLOW_CLI1	(ERROR_CODE_GROUP_MAILBOX + 0x11)
#define MB_ERROR__SET_RECORDING		(ERROR_CODE_GROUP_MAILBOX + 0x12)
#define MB_ERROR__MB_ID_NOT_FOUND	(ERROR_CODE_GROUP_MAILBOX + 0x20)
#define MB_ERROR__OVERRUN_MB_MALLOC	(ERROR_CODE_GROUP_MAILBOX + 0x21)
#define MB_ERROR__OVERRUN_MB_MALLOC1	(ERROR_CODE_GROUP_MAILBOX + 0x21)
#define MB_ERROR__OVERRUN_MB_MALLOC2	(ERROR_CODE_GROUP_MAILBOX + 0x22)
#define MB_ERROR__MB_COUNT		(ERROR_CODE_GROUP_MAILBOX + 0x23)
#define MB_ERROR__BAD_CORE_ID		(ERROR_CODE_GROUP_MAILBOX + 0x24)
#define MB_ERROR__DDF_MB_NOT_SAME_CORE	(ERROR_CODE_GROUP_MAILBOX + 0x25)


#define RTOS_ERROR__TASK_ID_RETURN_0	(ERROR_CODE_GROUP_RTOS + 0)
#define RTOS_ERROR__BAD_ADDON_NUM	(ERROR_CODE_GROUP_RTOS + 1)
#define RTOS_ERROR__BAD_TCB_SIGNATURE	(ERROR_CODE_GROUP_RTOS + 2)
#define RTOS_ERROR__BAD_ITEMS_COUNTER	(ERROR_CODE_GROUP_RTOS + 3)
#define RTOS_ERROR__ASSERT		(ERROR_CODE_GROUP_RTOS + 4)

/* DMEM related errors  */
#define DMEM_ERROR_OUT_OF_MEMORY        (ERROR_CODE_GROUP_DMEM + 0)
#define DMEM_ERROR_RELEASE_INTEGRITY    (ERROR_CODE_GROUP_DMEM + 7)

#define FB_ERROR_DSPG_NOT_RESPONDING    0x999

/* FB Addon messages */
#define FB_ADDON_USECASE_MANAGER_READY	0x1
#define FB_ADDON_ALGO_ENABLED	0x2
#define FB_ADDON_ALGO_DISABLED	0x3

#define FB_ADDON_AWB_LOADED	0xA
#endif /* _DBMD7_FW_API_H */
