/**
 * dbmd7_fw_const_extra.h
 *
 * Copyright (C) 2016 DSP Group
 * All rights reserved.
 *
 * Unauthorized copying of this file is strictly prohibited.
 */

#ifndef _DBMD7_FW_CONST_EXTRA_H
#define _DBMD7_FW_CONST_EXTRA_H

#define PRIORITY_RUN_ON_IDLE_LOOP	(1)
#define PRIORITY_RUN_ON_IDLE_ISR	(0)

#define WRITE_REG_TYPE_16		1
#define WRITE_REG_TYPE_32		2
#define WRITE_REG_TYPE_64		3
#define WRITE_REG_TYPE_96		4
#define WRITE_REG_MSLEEP_MSEC		5
#define WRITE_REG_DUMMY			6

#define READ_REG_TYPE_16		7
#define READ_REG_TYPE_32		8
#define READ_REG_TYPE_32_INDEX		9
#define READ_REG_TYPE_64		10
#define READ_REG_TYPE_64_INDEX		11


/* temporary till FW will define it */
#define MSG_FMT_SUBMODE_NO_ACTION		0x0
#define MSG_FMT_SUBMODE_GET_PENDING_MESSAGE	0x1
#define MSG_FMT_SUBMODE_GET_16BIT		0x2
#define MSG_FMT_SUBMODE_GET_32BIT		0x3
#define MSG_FMT_SUBMODE_GET_64BIT		0x4
#define MSG_SUBMODE_MASK			0xFFFF

#define MSG_ID_ADDON_SENSORY	5
#define MSG_ID_ADDON_ASRP	4

#define FW_TASK_ID__SPLITER	4

#define ASRP_FRAME_LEN			512
#define TDM_FRAME_LEN			512

#define ASRP_TDM_NUMBER_OF_CHANNELS	2
#define TDM_2_TDM_FRAME_LEN		1024
#define PRI_TDM_RX_BLK_NUM		0
#define TDM_MASTER			1
#define TDM_SLAVE			0


#define ATTRIB_DM_CLOCK_512kHz		0
#define ATTRIB_DM_CLOCK_768kHz		1
#define ATTRIB_DM_CLOCK_1024kHz		2
#define ATTRIB_DM_CLOCK_1536kHz		3
#define ATTRIB_DM_CLOCK_2048kHz		4
#define ATTRIB_DM_CLOCK_2304kHz		5
#define ATTRIB_DM_CLOCK_3072kHz		6

#define MB_NOTIFICATION_BIT_0		0
#define MB_NOTIFICATION_BIT_1		1
#define MB_MEM_LOC_BITN			28
#define MB_MEM_LOC_MASK			(3<<MB_MEM_LOC_BITN)

#define CORE_0			0
#define CORE_ID_BITS		27

#define CACHED_SHARED_MEMORY		0
#define	NON_CHACHED_SHARED_MEMORY	1
#define	SWITCHABLE_CACHED_SHARED_MEMORY	2
#define	MEMORY_DTCM			3

#define FW_RESMP_TASK_INPUT_MB		0x1
#define FW_RESMP_TASK_OUTPUT1_MB	0x3
#define FW_RESMP_TASK_OUTPUT2_MB	0x4

#define TASK_CONFIG_CREATE_CMD_AND_DATA(cmd, data)	\
				(((cmd & 0xFF)<<24) | (data & 0xFFFFFF))

#define TDM_MB_CONFIG_MB_SIZE_2_FRAMES 0
#define TDM_MB_CONFIG_BYPASS           7

/* word 5 -- 28,29*/
#define TDM_MB_MEM_LOC_BITN		28
#define TDM_MB_MEM_LOC_MASK		(3<<TDM_MB_MEM_LOC_BITN)

#define TDM_CONFIG_POLICY_SIMPLE_COPY_32	0
#define TDM_CONFIG_POLICY_FIFO_16_SAMPLES	1

#define MB_MEM_TYPE_BITS		28
#define MB_MEM_TYPE_SHARED_NO_CACHE	1

#define MB_CREATE_WORD1_OWNER_CORE_BITN	16



#define ASRP_OUT_MB_ID			0x81
#define ASRP_PARAM_MB_ID		0x82
#define MIXER_OUT_MB_ID			0x88
#define DECIMATOR_OUT_MB_ID		0x89


#define USER_ADDON_TASK_CMD_KILL_TASK			0
#define USER_ADDON_TASK_CMD_MIC_MB_ID			1
#define USER_ADDON_TASK_CMD_PASSPHRASE_MB_ID		2
#define USER_ADDON_TASK_CMD_COMMAND_MB_ID		3
#define USER_ADDON_TASK_CMD_REGISTERS_MB_ID		4
#define USER_ADDON_TASK_CMD_PASSPHRASE_LOADED_IND	5
#define USER_ADDON_TASK_CMD_COMMAND_LOADED_IND		6

#define USER_ADDON_TASK_CMD_MIC_MB_ID			1
#define USER_ADDON_TASK_CMD_REFERENCE_TDM_MB_ID		2
#define USER_ADDON_TASK_CMD_OUTPUT_MB_ID		3
#define USER_ADDON_TASK_CMD_ASRP_PARAM_MB_ID		4
#define USER_ADDON_TASK_CMD_ASRP_PARAM_LOADED_IND	5


#define USER_ADDON_TASK_CMD_KILL_TASK			0
#define USER_ADDON_TASK_CMD_MB_IN1_ID			1
#define USER_ADDON_TASK_CMD_MB_IN2_ID			2
#define USER_ADDON_TASK_CMD_MB_OUT_ID			3



#define SENSORY_FRAME_LEN			0xF0

#define SENSORY_REG_MB_ID			0x91
#define SENSORY_PASSPHRASE_MB_ID		0x92
#define SENSORY_CMD_MB_ID			0x93
#define SENSORY_PASSPHRASE_IND			0x94


#endif /* _DBMD7_FW_CONST_EXTRA_H */
