dtb-$(CONFIG_ARCH_MSM8998) += \
        apq8098-aloha-evt1-pre.dtb \
        apq8098-aloha-evt1.dtb \
        apq8098-aloha-evt2.dtb \
        apq8098-ohana-proto.dtb \

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files := *.dtb
