dbmdx-core-objs := dbmdx.o dbmdx-spi.o dbmdx-spi-d7.o dbmdx-chip-interfaces.o \
				dbmdx-fw-cmd-interface.o dbmdx-clocks.o dbmdx-customer.o \
				dbmdx-sysfs.o dbmdx-of.o dbmdx-usecases.o dbmdx-utils.o dbmdx-common-operations.o

obj-$(CONFIG_MFD_DBMDX) 	+= dbmdx-core.o
obj-$(CONFIG_DBMDX_MHA)		+= dbmdx-mha.o
obj-$(CONFIG_DBMDX_STAX)	+= dbmdx-stax.o
