#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-$(CONFIG_TOUCHSCREEN_FTS_INTERNAL_DEBUG) += focaltech_test_ft5826s.o
obj-$(CONFIG_TOUCHSCREEN_FTS_INTERNAL_DEBUG) += focaltech_test_config_ft5826s.o
obj-$(CONFIG_TOUCHSCREEN_FTS_INTERNAL_DEBUG) += focaltech_test_supported_ic.o

