#
# Makefile for MELFAS MIP4 Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIP4) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS427) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438S) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449S) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms449s.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS458) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS500) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms500.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS587N) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms587n.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS600) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms600.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MCS6000) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mcs6000.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MCS8040L) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mcs8040l.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MFS10) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mfs10.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MFS10VE) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mfs10.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MOS50) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mos50.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT200) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mit200.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT300) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mit300.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT400) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mit400.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT401) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mit401.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT410) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mit400.o mip4_ts_autotest.o

