/*
 * Copyright by ams AG
 * All rights are reserved.
 *
 * IMPORTANT - PLEASE READ CAREFULLY BEFORE COPYING, INSTALLING OR USING
 * THE SOFTWARE.
 *
 * THIS SOFTWARE IS PROVIDED FOR USE ONLY IN CONJUNCTION WITH AMS PRODUCTS.
 * USE OF THE SOFTWARE IN CONJUNCTION WITH NON-AMS-PRODUCTS IS EXPLICITLY
 * EXCLUDED.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __AMS_SMUX_CONFIGS_H
#define __AMS_SMUX_CONFIGS_H

#define SMUX_SIZE (20)

enum als_channel_config {
    ALS_SMUX_CFG_1,
    ALS_SMUX_CFG_2,
    ALS_SMUX_CFG_MAX = ALS_SMUX_CFG_2 + 1,
    ALS_SMUX_CFG_DFLT = ALS_SMUX_CFG_1
};

static u8 smux_config_data[ALS_SMUX_CFG_MAX][SMUX_SIZE] = {
    {	/* F1 -> ADC0, F2 -> ADC1, F3-> ADC2, F4 -> ADC3, CLEAR -> ADC4, NIR -> ADC5 */
        0x30, 0x01, 0x00, 0x00,
        0x00, 0x42, 0x00, 0x00,
        0x50, 0x00, 0x00, 0x00,
        0x20, 0x04, 0x00, 0x30,
        0x01, 0x50, 0x00, 0x06
    },
    {	/* F5 -> ADC0, F6 -> ADC1, F7-> ADC2, F8 -> ADC3, CLEAR -> ADC4, NIR -> ADC5 */
        0x00, 0x00, 0x00, 0x40,
        0x02, 0x00, 0x10, 0x03,
        0x50, 0x10, 0x03, 0x00,
        0x00, 0x00, 0x24, 0x00,
        0x00, 0x50, 0x00, 0x06
    }
};



#endif
