#
# Makefile for Bosch sensor driver.
#

obj-$(CONFIG_BOSCH_DRIVER_LOG_FUNC) += bs_log.o

obj-$(CONFIG_BMA4XY_ACCEL)	+= bma4xy_driver.o bma4.o bma456h.o
obj-$(CONFIG_BMA4XY_ACCEL)	+= bma4xy_i2c.o
obj-$(CONFIG_BMA4XY_ACCEL_SPI)	+= bma4xy_spi.o
