#
# Makefile for SiW touch driver
#

obj-$(CONFIG_TOUCHSCREEN_SIW) := siw_touch.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_hal.o siw_touch_hal_sysfs.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_hal_abt.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_hal_prd.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_hal_watch.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_bus.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_bus_i2c.o siw_touch_bus_spi.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_of.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_irq.o siw_touch_gpio.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_event.o siw_touch_notify.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_sys.o siw_touch_sysfs.o
obj-$(CONFIG_TOUCHSCREEN_SIW) += siw_touch_misc.o

obj-$(CONFIG_TOUCHSCREEN_SIW_LG4894) += touch_lg4894.o
obj-$(CONFIG_TOUCHSCREEN_SIW_LG4895) += touch_lg4895.o
obj-$(CONFIG_TOUCHSCREEN_SIW_LG4946) += touch_lg4946.o
obj-$(CONFIG_TOUCHSCREEN_SIW_LG4951) += touch_lg4951.o
obj-$(CONFIG_TOUCHSCREEN_SIW_SW1828) += touch_sw1828.o
obj-$(CONFIG_TOUCHSCREEN_SIW_SW49407) += touch_sw49407.o
obj-$(CONFIG_TOUCHSCREEN_SIW_SW42101) += touch_sw42101.o

obj-$(CONFIG_TOUCHSCREEN_SIWMON) += mon/

